# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160829_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='date',
            field=models.DateField(),
        ),
    ]
