# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrance',
            options={'ordering': ['date'], 'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['description'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='productentrance',
            options={'verbose_name': 'entrada produto', 'verbose_name_plural': 'entrada produtos'},
        ),
        migrations.AlterModelOptions(
            name='productsale',
            options={'verbose_name': 'item venda', 'verbose_name_plural': 'itens venda'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['sale_number'], 'verbose_name': 'venda', 'verbose_name_plural': 'vendas'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
        migrations.AlterField(
            model_name='entrance',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='document_number',
            field=models.CharField(max_length=20, verbose_name='nf'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='código barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supplier', verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='productentrance',
            name='entrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entrance', verbose_name='entrada'),
        ),
        migrations.AlterField(
            model_name='productentrance',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='productentrance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='productentrance',
            name='quantity',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='quantity',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sale', verbose_name='venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(verbose_name='data venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='desconto'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(max_length=20, verbose_name='venda'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='data_register',
            field=models.DateField(auto_now_add=True, verbose_name='data cadastro'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='fornecedor'),
        ),
    ]
