# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160912_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='data venda'),
        ),
    ]
